#!/bin/bash

# Proof of concept do biglinux-tube

# Objetivo: pesquisar por termo no youtube e criar html com título do vídeo, thumbnail, descrição e link do vídeo

# TODO: embutir vídeo no html ou reproduzir vídeo pelo mpv

# Dependências: yt-dlp, jq, gawk

rm -f search.sh.htm

# Qual plataforma buscar (yt=YouTube, gv=Google Video)
# Which platform to search in
platform=yt

# Termos que serão pesquisados
# Search terms
searchterms="big linux manjaro"

# Quantidade de resultados
# Number of results
noresults=5

#yt-dlp ${platform}search${noresults}:"${searchterms}" --get-id --get-thumbnail --get-title --get-description


yt-dlp ${platform}search${noresults}:"${searchterms}" -j | jq -rM .id,.thumbnail,.title,.channel,.view_count,.description,.id |
gawk -v platform="${platform}" -v noresults="${noresults}" -v searchterms="${searchterms}" -- '
### Begin awk script

BEGIN {
# This OFS allows readable code during printing
  OFS = "\n"

  print(\
"<html><head><style>",
"td {",
"  vertical-align: top;",
"}",
"",
"td {",
"  border: 1px solid;",
"}",
"</style></head><body><table>",
"<h1>Procurando por <i>" searchterms "</i> no " ( platform == "yt" ? "YouTube" : "Google Video" )  ":</h1>") > "search.sh.htm"
}

!id {
  id = $0
  next
}

!thumbnail {
  thumbnail = $0
  next
}

!title {
  title = $0
  next
}

!channel {
  channel = $0
  next
}

!views {
  views = $0
  next
}

$0 !~ "^" id "$" {
  description = description $0 "<br>"
  next
}

{
  # Prints html
  print(\
"<tr>",
"<td><a href=\"https://www.youtube.com/watch?v=" id "\"><img src=\"" thumbnail "\" width=\"480\" height=\"360\"></a></td>",
"<td><h2><a href=\"https://www.youtube.com/watch?v=" id "\">" title "</a></h2>",
"<h3>" channel " - " views " visualizações</h3>",
"<p>" description "</p></td>",
"</tr>") > "search.sh.htm"
  id = thumbnail = title = channel = views = description = ""
  next
}

END {
  print("</table></body></html>") > "search.sh.htm"
}

'
### End gawk script
